# extlinux configuration booting firmware slot B — see extlinux-a.conf
# for the notes.
DEFAULT nerves-b
TIMEOUT 1

LABEL nerves-b
    KERNEL /Image.b
    FDT /sun50i-h618-kickpi-k2b.b.dtb
    APPEND console=ttyS0,115200 console=tty1 root=PARTUUID=4b326232-03 rootfstype=squashfs rootwait
